server:
  port: 8803
spring:
  application:
    name: eureka-service
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    #serviceUrl:
    #  defaultZone: http://${register.center.host}:${register.center.port}/eureka
    region: region1
    availabilityZones:
      region1: zone1,zone2
    serviceUrl:
      zone1: http://${register.center.host}:${register.center.port}/eureka
      zone2: http://${register.center.host}:${register.center.port}/eureka
