package mybatis.dao;

import mybatis.dto.MybatisTable2;
import mybatis.dto.MybatisTable2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MybatisTable2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    long countByExample(MybatisTable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int deleteByExample(MybatisTable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int insert(MybatisTable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int insertSelective(MybatisTable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    List<MybatisTable2> selectByExample(MybatisTable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    MybatisTable2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByExampleSelective(@Param("record") MybatisTable2 record, @Param("example") MybatisTable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByExample(@Param("record") MybatisTable2 record, @Param("example") MybatisTable2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByPrimaryKeySelective(MybatisTable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByPrimaryKey(MybatisTable2 record);
}