package com.k.web.mybatis.mybatis.mapper;

import com.k.web.mybatis.mybatis.model.MybatisTable1;
import com.k.web.mybatis.mybatis.model.MybatisTable1Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MybatisTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    long countByExample(MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    int deleteByExample(MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    int insert(MybatisTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    int insertSelective(MybatisTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    List<MybatisTable1> selectByExample(MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    int updateByExampleSelective(@Param("record") MybatisTable1 record, @Param("example") MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    int updateByExample(@Param("record") MybatisTable1 record, @Param("example") MybatisTable1Example example);
}