mongo.replica-set=192.168.64.229:27017,192.168.64.229:27018,192.168.64.229:27019
#mongo.replica-set=192.168.2.61:27017,192.168.2.61:27018,192.168.2.61:27019
mongo.connections-per-host=5
mongo.threads-allowed-to-block-for-connection-multiplier=10
mongo.connect-timeout=100
mongo.auto-connect-retry=true
mongo.socket-keep-alive=true
mongo.socket-timeout=100000
mongo.slave-ok=true
mongo.write-number=2
mongo.write-timeout=3000
mongo.write-fsync=false
mongo.dbname=ceshi
mongo.authentication-dbname=admin
mongo.username=admin
mongo.password=admin
 