server:
  port: 8884
spring:
  application:
    name: feign-nacos-server
  cloud:
    nacos:
      discovery:
        serverAddr: nacos:8848
  sentinel:
    enabled: true
    transport:
      #port: 8900
      dashboard: sentinel:9930
      feign:
        client:
          config:
            feignName:
  boot:
    admin:
      client:
        url: http://smp:8980