server:
  port: ${random.int[10000,19999]}
spring:
  application:
    name: feign-server
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    #    region : region2
    #    serviceUrl:
    #      defaultZone: http://${register.center.host}:${register.center.port}/eureka
    #      region2: http://${register.center.host}:${register.center.port}/eureka

    region: region1
    availabilityZones:
      region1: zone2
    serviceUrl:
      #zone1: http://${register.center.host}:${register.center.port}/eureka
      zone2: http://${register.center.host}:${register.center.port}/eureka
