server:
  port: 8806
spring:
  application:
    name: sleuth_server
  cloud:
    nacos:
      discovery:
        serverAddr: nacos:8848
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    enabled: true