#NacosDiscoveryProperties
server:
  port: 8901
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
  boot:
    admin:
      client:
        url: http://smp:8980