package com.k.web.mybatis.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MybatisTable2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public MybatisTable2Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andId2IsNull() {
            addCriterion("id2 is null");
            return (Criteria) this;
        }

        public Criteria andId2IsNotNull() {
            addCriterion("id2 is not null");
            return (Criteria) this;
        }

        public Criteria andId2EqualTo(Integer value) {
            addCriterion("id2 =", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotEqualTo(Integer value) {
            addCriterion("id2 <>", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2GreaterThan(Integer value) {
            addCriterion("id2 >", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2GreaterThanOrEqualTo(Integer value) {
            addCriterion("id2 >=", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2LessThan(Integer value) {
            addCriterion("id2 <", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2LessThanOrEqualTo(Integer value) {
            addCriterion("id2 <=", value, "id2");
            return (Criteria) this;
        }

        public Criteria andId2In(List<Integer> values) {
            addCriterion("id2 in", values, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotIn(List<Integer> values) {
            addCriterion("id2 not in", values, "id2");
            return (Criteria) this;
        }

        public Criteria andId2Between(Integer value1, Integer value2) {
            addCriterion("id2 between", value1, value2, "id2");
            return (Criteria) this;
        }

        public Criteria andId2NotBetween(Integer value1, Integer value2) {
            addCriterion("id2 not between", value1, value2, "id2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2IsNull() {
            addCriterion("mybatis_id2 is null");
            return (Criteria) this;
        }

        public Criteria andMybatisId2IsNotNull() {
            addCriterion("mybatis_id2 is not null");
            return (Criteria) this;
        }

        public Criteria andMybatisId2EqualTo(Integer value) {
            addCriterion("mybatis_id2 =", value, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2NotEqualTo(Integer value) {
            addCriterion("mybatis_id2 <>", value, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2GreaterThan(Integer value) {
            addCriterion("mybatis_id2 >", value, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2GreaterThanOrEqualTo(Integer value) {
            addCriterion("mybatis_id2 >=", value, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2LessThan(Integer value) {
            addCriterion("mybatis_id2 <", value, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2LessThanOrEqualTo(Integer value) {
            addCriterion("mybatis_id2 <=", value, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2In(List<Integer> values) {
            addCriterion("mybatis_id2 in", values, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2NotIn(List<Integer> values) {
            addCriterion("mybatis_id2 not in", values, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2Between(Integer value1, Integer value2) {
            addCriterion("mybatis_id2 between", value1, value2, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisId2NotBetween(Integer value1, Integer value2) {
            addCriterion("mybatis_id2 not between", value1, value2, "mybatisId2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2IsNull() {
            addCriterion("mybatis_name2 is null");
            return (Criteria) this;
        }

        public Criteria andMybatisName2IsNotNull() {
            addCriterion("mybatis_name2 is not null");
            return (Criteria) this;
        }

        public Criteria andMybatisName2EqualTo(String value) {
            addCriterion("mybatis_name2 =", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2NotEqualTo(String value) {
            addCriterion("mybatis_name2 <>", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2GreaterThan(String value) {
            addCriterion("mybatis_name2 >", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2GreaterThanOrEqualTo(String value) {
            addCriterion("mybatis_name2 >=", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2LessThan(String value) {
            addCriterion("mybatis_name2 <", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2LessThanOrEqualTo(String value) {
            addCriterion("mybatis_name2 <=", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2Like(String value) {
            addCriterion("mybatis_name2 like", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2NotLike(String value) {
            addCriterion("mybatis_name2 not like", value, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2In(List<String> values) {
            addCriterion("mybatis_name2 in", values, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2NotIn(List<String> values) {
            addCriterion("mybatis_name2 not in", values, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2Between(String value1, String value2) {
            addCriterion("mybatis_name2 between", value1, value2, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisName2NotBetween(String value1, String value2) {
            addCriterion("mybatis_name2 not between", value1, value2, "mybatisName2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2IsNull() {
            addCriterion("mybatis_time2 is null");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2IsNotNull() {
            addCriterion("mybatis_time2 is not null");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2EqualTo(Date value) {
            addCriterion("mybatis_time2 =", value, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2NotEqualTo(Date value) {
            addCriterion("mybatis_time2 <>", value, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2GreaterThan(Date value) {
            addCriterion("mybatis_time2 >", value, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2GreaterThanOrEqualTo(Date value) {
            addCriterion("mybatis_time2 >=", value, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2LessThan(Date value) {
            addCriterion("mybatis_time2 <", value, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2LessThanOrEqualTo(Date value) {
            addCriterion("mybatis_time2 <=", value, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2In(List<Date> values) {
            addCriterion("mybatis_time2 in", values, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2NotIn(List<Date> values) {
            addCriterion("mybatis_time2 not in", values, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2Between(Date value1, Date value2) {
            addCriterion("mybatis_time2 between", value1, value2, "mybatisTime2");
            return (Criteria) this;
        }

        public Criteria andMybatisTime2NotBetween(Date value1, Date value2) {
            addCriterion("mybatis_time2 not between", value1, value2, "mybatisTime2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mybatis_table_2
     *
     * @mbg.generated do_not_delete_during_merge 2018-11-04 22:52:46
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}