package com.k.web.mybatis.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class MybatisTable2 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_table_2.id2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    private Integer id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_table_2.mybatis_id2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    private Integer mybatisId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_table_2.mybatis_name2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    private String mybatisName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_table_2.mybatis_time2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    private Date mybatisTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_table_2.id2
     *
     * @return the value of mybatis_table_2.id2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_table_2.id2
     *
     * @param id2 the value for mybatis_table_2.id2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setId2(Integer id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_table_2.mybatis_id2
     *
     * @return the value of mybatis_table_2.mybatis_id2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Integer getMybatisId2() {
        return mybatisId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_table_2.mybatis_id2
     *
     * @param mybatisId2 the value for mybatis_table_2.mybatis_id2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setMybatisId2(Integer mybatisId2) {
        this.mybatisId2 = mybatisId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_table_2.mybatis_name2
     *
     * @return the value of mybatis_table_2.mybatis_name2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public String getMybatisName2() {
        return mybatisName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_table_2.mybatis_name2
     *
     * @param mybatisName2 the value for mybatis_table_2.mybatis_name2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setMybatisName2(String mybatisName2) {
        this.mybatisName2 = mybatisName2 == null ? null : mybatisName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_table_2.mybatis_time2
     *
     * @return the value of mybatis_table_2.mybatis_time2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Date getMybatisTime2() {
        return mybatisTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_table_2.mybatis_time2
     *
     * @param mybatisTime2 the value for mybatis_table_2.mybatis_time2
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setMybatisTime2(Date mybatisTime2) {
        this.mybatisTime2 = mybatisTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MybatisTable2 other = (MybatisTable2) that;
        return (this.getId2() == null ? other.getId2() == null : this.getId2().equals(other.getId2()))
                && (this.getMybatisId2() == null ? other.getMybatisId2() == null : this.getMybatisId2().equals(other.getMybatisId2()))
                && (this.getMybatisName2() == null ? other.getMybatisName2() == null : this.getMybatisName2().equals(other.getMybatisName2()))
                && (this.getMybatisTime2() == null ? other.getMybatisTime2() == null : this.getMybatisTime2().equals(other.getMybatisTime2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId2() == null) ? 0 : getId2().hashCode());
        result = prime * result + ((getMybatisId2() == null) ? 0 : getMybatisId2().hashCode());
        result = prime * result + ((getMybatisName2() == null) ? 0 : getMybatisName2().hashCode());
        result = prime * result + ((getMybatisTime2() == null) ? 0 : getMybatisTime2().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_2
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id2=").append(id2);
        sb.append(", mybatisId2=").append(mybatisId2);
        sb.append(", mybatisName2=").append(mybatisName2);
        sb.append(", mybatisTime2=").append(mybatisTime2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}