package com.k.spring.boot.mybatis.dao;

import com.k.spring.boot.mybatis.dto.Blog1;
import com.k.spring.boot.mybatis.dto.Blog1Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Blog1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    long countByExample(Blog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int deleteByExample(Blog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int insert(Blog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int insertSelective(Blog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    List<Blog1> selectByExample(Blog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    Blog1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByExampleSelective(@Param("record") Blog1 record, @Param("example") Blog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByExample(@Param("record") Blog1 record, @Param("example") Blog1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByPrimaryKeySelective(Blog1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog1
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByPrimaryKey(Blog1 record);
}