package com.k.spring.boot.mybatis.dao;

import com.k.spring.boot.mybatis.dto.Blog2;
import com.k.spring.boot.mybatis.dto.Blog2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Blog2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    long countByExample(Blog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int deleteByExample(Blog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int insert(Blog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int insertSelective(Blog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    List<Blog2> selectByExample(Blog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    Blog2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByExampleSelective(@Param("record") Blog2 record, @Param("example") Blog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByExample(@Param("record") Blog2 record, @Param("example") Blog2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByPrimaryKeySelective(Blog2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    int updateByPrimaryKey(Blog2 record);
}