mongo.replica-set=192.168.2.16:27017,192.168.2.16:27018,192.168.2.16:27019
mongo.connections-per-host=5
mongo.threads-allowed-to-block-for-connection-multiplier=10
mongo.connect-timeout=500
mongo.auto-connect-retry=true
mongo.socket-keep-alive=true
mongo.socket-timeout=600
mongo.slave-ok=true
