package com.k.spring.boot.mybatis.dto;

import java.io.Serializable;
import java.util.Date;

public class Blog2 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog2.id
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog2.sum_num
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    private Integer sumNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog2.blog_name
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    private String blogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog2.blog_time
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    private Date blogTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog2.id
     *
     * @return the value of blog2.id
     * @mbg.generated 2019-05-10 17:09:30
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog2.id
     *
     * @param id the value for blog2.id
     * @mbg.generated 2019-05-10 17:09:30
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog2.sum_num
     *
     * @return the value of blog2.sum_num
     * @mbg.generated 2019-05-10 17:09:30
     */
    public Integer getSumNum() {
        return sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog2.sum_num
     *
     * @param sumNum the value for blog2.sum_num
     * @mbg.generated 2019-05-10 17:09:30
     */
    public void setSumNum(Integer sumNum) {
        this.sumNum = sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog2.blog_name
     *
     * @return the value of blog2.blog_name
     * @mbg.generated 2019-05-10 17:09:30
     */
    public String getBlogName() {
        return blogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog2.blog_name
     *
     * @param blogName the value for blog2.blog_name
     * @mbg.generated 2019-05-10 17:09:30
     */
    public void setBlogName(String blogName) {
        this.blogName = blogName == null ? null : blogName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog2.blog_time
     *
     * @return the value of blog2.blog_time
     * @mbg.generated 2019-05-10 17:09:30
     */
    public Date getBlogTime() {
        return blogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog2.blog_time
     *
     * @param blogTime the value for blog2.blog_time
     * @mbg.generated 2019-05-10 17:09:30
     */
    public void setBlogTime(Date blogTime) {
        this.blogTime = blogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Blog2 other = (Blog2) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getSumNum() == null ? other.getSumNum() == null : this.getSumNum().equals(other.getSumNum()))
                && (this.getBlogName() == null ? other.getBlogName() == null : this.getBlogName().equals(other.getBlogName()))
                && (this.getBlogTime() == null ? other.getBlogTime() == null : this.getBlogTime().equals(other.getBlogTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSumNum() == null) ? 0 : getSumNum().hashCode());
        result = prime * result + ((getBlogName() == null) ? 0 : getBlogName().hashCode());
        result = prime * result + ((getBlogTime() == null) ? 0 : getBlogTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog2
     *
     * @mbg.generated 2019-05-10 17:09:30
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sumNum=").append(sumNum);
        sb.append(", blogName=").append(blogName);
        sb.append(", blogTime=").append(blogTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}