package com.k.spring.boot.mybatis.dto;

import java.io.Serializable;

public class Tb implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb
     *
     * @mbg.generated 2017-10-29 00:41:46
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb.id
     *
     * @mbg.generated 2017-10-29 00:41:46
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb.tbname
     *
     * @mbg.generated 2017-10-29 00:41:46
     */
    private String tbname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb.id
     *
     * @return the value of tb.id
     * @mbg.generated 2017-10-29 00:41:46
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb.id
     *
     * @param id the value for tb.id
     * @mbg.generated 2017-10-29 00:41:46
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb.tbname
     *
     * @return the value of tb.tbname
     * @mbg.generated 2017-10-29 00:41:46
     */
    public String getTbname() {
        return tbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb.tbname
     *
     * @param tbname the value for tb.tbname
     * @mbg.generated 2017-10-29 00:41:46
     */
    public void setTbname(String tbname) {
        this.tbname = tbname == null ? null : tbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-10-29 00:41:46
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tb other = (Tb) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getTbname() == null ? other.getTbname() == null : this.getTbname().equals(other.getTbname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-10-29 00:41:46
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTbname() == null) ? 0 : getTbname().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-10-29 00:41:46
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tbname=").append(tbname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}