package mybatis.dao;

import mybatis.dto.MybatisTable1;
import mybatis.dto.MybatisTable1Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MybatisTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    long countByExample(MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int deleteByExample(MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int insert(MybatisTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int insertSelective(MybatisTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    List<MybatisTable1> selectByExample(MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    MybatisTable1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByExampleSelective(@Param("record") MybatisTable1 record, @Param("example") MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByExample(@Param("record") MybatisTable1 record, @Param("example") MybatisTable1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByPrimaryKeySelective(MybatisTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2019-02-16 14:15:16
     */
    int updateByPrimaryKey(MybatisTable1 record);
}