server:
  port: 8804
spring:
  application:
    name: grpc-consumer
  cloud:
    nacos:
      discovery:
        serverAddr: nacos:8848
  sentinel:
    enabled: true
    transport:
      #port: 8900
      dashboard: sentinel:9930
  boot:
    admin:
      client:
        url: http://smp:8980
grpc:
  client:
    GLOBAL:
      security:
        enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext