server:
  port: 8080
database:
  primary:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/test1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 111111
  secondary:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/test2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 111111
mybatis:
  typeAliasesPackage: com.k.atomikos.repository.primary
  mapperLocations: classpath:mapper/Test1Mapper.xml
  createSqlSessionTemplate: false
  typeAliasesPackage2: com.k.atomikos.repository.secondary
  mapperLocations2: classpath:mapper/Test2Mapper.xml
