server:
  port: ${random.int[10000,19999]}
spring:
  application:
    name: feign-server
eureka:
  instance:
    metadataMap:
      zone: zone3
  client:
    #    region : region2
    #    serviceUrl:
    #      defaultZone: http://${register.center.host}:${register.center.port}/eureka
    #      region2: http://${register.center.host}:${register.center.port}/eureka

    region: region2
    availabilityZones:
      region2: zone3
    serviceUrl:
      #zone1: http://${register.center.host}:${register.center.port}/eureka
      zone3: http://${register.center.host}:${register.center.port}/eureka
