server:
  port: 8803
spring:
  application:
    name: grpc-provider
  cloud:
    nacos:
      discovery:
        serverAddr: nacos:8848
  sentinel:
    enabled: true
    transport:
      #port: 8900
      dashboard: sentinel:9930
  boot:
    admin:
      client:
        url: http://smp:8980
grpc:
  server:
    port: 9898