package com.k.spring.boot.mybatis.dao;

import com.k.spring.boot.mybatis.dto.Tb;
import com.k.spring.boot.mybatis.dto.TbExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    long countByExample(TbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    int deleteByExample(TbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    int insert(Tb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    int insertSelective(Tb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    List<Tb> selectByExample(TbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    int updateByExampleSelective(@Param("record") Tb record, @Param("example") TbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb
     *
     * @mbg.generated 2017-09-28 00:28:04
     */
    int updateByExample(@Param("record") Tb record, @Param("example") TbExample example);
}