mongodbRep.repName=node64
mongodbRep.port=27017
mongodbRep.priority=1
mongodbRep.host0=192.168.2.64
mongodbRep.port0=27017
mongodbRep.priority0=21
mongodbRep.host1=192.168.2.64
mongodbRep.port1=27018
mongodbRep.priority1=31
mongodbRep.host2=192.168.2.64
mongodbRep.port2=27019
mongodbRep.priority2=41


