spring:
  aop:
    auto: false
    proxy-target-class: true
server:
  port: 8081
my:
  servers:
    - dev.bar.com
    - foo.bar.com
#my.servers[0]=dev.bar.com
#my.servers[1]=foo.bar.com

environments:
  dev:
    url: http://dev.bar.com
    name: Developer Setup
  prod:
    url: http://foo.bar.com
    name: My Cool App
  product: pud
#environments.dev.url=http://dev.bar.com
#environments.dev.name=Developer Setup
#environments.prod.url=http://foo.bar.com
#environments.prod.name=My Cool App

#spring.ldap.urls=ldap://127.0.0.1:12345
#spring.ldap.username=admin
#spring.ldap.password=admin