package com.k.web.mybatis.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MybatisTable1Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public MybatisTable1Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andId1IsNull() {
            addCriterion("id1 is null");
            return (Criteria) this;
        }

        public Criteria andId1IsNotNull() {
            addCriterion("id1 is not null");
            return (Criteria) this;
        }

        public Criteria andId1EqualTo(Integer value) {
            addCriterion("id1 =", value, "id1");
            return (Criteria) this;
        }

        public Criteria andId1NotEqualTo(Integer value) {
            addCriterion("id1 <>", value, "id1");
            return (Criteria) this;
        }

        public Criteria andId1GreaterThan(Integer value) {
            addCriterion("id1 >", value, "id1");
            return (Criteria) this;
        }

        public Criteria andId1GreaterThanOrEqualTo(Integer value) {
            addCriterion("id1 >=", value, "id1");
            return (Criteria) this;
        }

        public Criteria andId1LessThan(Integer value) {
            addCriterion("id1 <", value, "id1");
            return (Criteria) this;
        }

        public Criteria andId1LessThanOrEqualTo(Integer value) {
            addCriterion("id1 <=", value, "id1");
            return (Criteria) this;
        }

        public Criteria andId1In(List<Integer> values) {
            addCriterion("id1 in", values, "id1");
            return (Criteria) this;
        }

        public Criteria andId1NotIn(List<Integer> values) {
            addCriterion("id1 not in", values, "id1");
            return (Criteria) this;
        }

        public Criteria andId1Between(Integer value1, Integer value2) {
            addCriterion("id1 between", value1, value2, "id1");
            return (Criteria) this;
        }

        public Criteria andId1NotBetween(Integer value1, Integer value2) {
            addCriterion("id1 not between", value1, value2, "id1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1IsNull() {
            addCriterion("mybatis_id1 is null");
            return (Criteria) this;
        }

        public Criteria andMybatisId1IsNotNull() {
            addCriterion("mybatis_id1 is not null");
            return (Criteria) this;
        }

        public Criteria andMybatisId1EqualTo(Integer value) {
            addCriterion("mybatis_id1 =", value, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1NotEqualTo(Integer value) {
            addCriterion("mybatis_id1 <>", value, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1GreaterThan(Integer value) {
            addCriterion("mybatis_id1 >", value, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1GreaterThanOrEqualTo(Integer value) {
            addCriterion("mybatis_id1 >=", value, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1LessThan(Integer value) {
            addCriterion("mybatis_id1 <", value, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1LessThanOrEqualTo(Integer value) {
            addCriterion("mybatis_id1 <=", value, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1In(List<Integer> values) {
            addCriterion("mybatis_id1 in", values, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1NotIn(List<Integer> values) {
            addCriterion("mybatis_id1 not in", values, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1Between(Integer value1, Integer value2) {
            addCriterion("mybatis_id1 between", value1, value2, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisId1NotBetween(Integer value1, Integer value2) {
            addCriterion("mybatis_id1 not between", value1, value2, "mybatisId1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1IsNull() {
            addCriterion("mybatis_name1 is null");
            return (Criteria) this;
        }

        public Criteria andMybatisName1IsNotNull() {
            addCriterion("mybatis_name1 is not null");
            return (Criteria) this;
        }

        public Criteria andMybatisName1EqualTo(String value) {
            addCriterion("mybatis_name1 =", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1NotEqualTo(String value) {
            addCriterion("mybatis_name1 <>", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1GreaterThan(String value) {
            addCriterion("mybatis_name1 >", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1GreaterThanOrEqualTo(String value) {
            addCriterion("mybatis_name1 >=", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1LessThan(String value) {
            addCriterion("mybatis_name1 <", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1LessThanOrEqualTo(String value) {
            addCriterion("mybatis_name1 <=", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1Like(String value) {
            addCriterion("mybatis_name1 like", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1NotLike(String value) {
            addCriterion("mybatis_name1 not like", value, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1In(List<String> values) {
            addCriterion("mybatis_name1 in", values, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1NotIn(List<String> values) {
            addCriterion("mybatis_name1 not in", values, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1Between(String value1, String value2) {
            addCriterion("mybatis_name1 between", value1, value2, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisName1NotBetween(String value1, String value2) {
            addCriterion("mybatis_name1 not between", value1, value2, "mybatisName1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1IsNull() {
            addCriterion("mybatis_time1 is null");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1IsNotNull() {
            addCriterion("mybatis_time1 is not null");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1EqualTo(Date value) {
            addCriterion("mybatis_time1 =", value, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1NotEqualTo(Date value) {
            addCriterion("mybatis_time1 <>", value, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1GreaterThan(Date value) {
            addCriterion("mybatis_time1 >", value, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1GreaterThanOrEqualTo(Date value) {
            addCriterion("mybatis_time1 >=", value, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1LessThan(Date value) {
            addCriterion("mybatis_time1 <", value, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1LessThanOrEqualTo(Date value) {
            addCriterion("mybatis_time1 <=", value, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1In(List<Date> values) {
            addCriterion("mybatis_time1 in", values, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1NotIn(List<Date> values) {
            addCriterion("mybatis_time1 not in", values, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1Between(Date value1, Date value2) {
            addCriterion("mybatis_time1 between", value1, value2, "mybatisTime1");
            return (Criteria) this;
        }

        public Criteria andMybatisTime1NotBetween(Date value1, Date value2) {
            addCriterion("mybatis_time1 not between", value1, value2, "mybatisTime1");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mybatis_table_1
     *
     * @mbg.generated do_not_delete_during_merge 2018-11-04 22:52:46
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mybatis_table_1
     *
     * @mbg.generated 2018-11-04 22:52:46
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}